baseURL = "http://staff.ustc.edu.cn/~xll/"
languageCode = "en-us"
title = "Lailin Xu"
#theme = "starter-academic"
#theme = "researcher"
theme = "minimal"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
